import type { Metadata } from "next";
import { Lato, Honk } from "next/font/google";
import "./globals.css";

const latoSans = Lato({
  variable: "--font-lato-sans",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

const honkSans = Honk({
  variable: "--font-honk-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hoooje",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${latoSans.variable} ${honkSans.variable} antialiased`}>
        <div className="h-full w-full flex flex-row justify-center p-6">
          <main className="w-full md:max-w-lg flex flex-col">
            <span className={`${honkSans.className} text-4xl`}>HOOOJE</span>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
