import type { MetadataRoute } from "next";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: [
        "/",
        "/baht-tailandes",
        "/binance-coin",
        "/binance-coing-dolar",
        "/binance-coin-euro",
        "/bitcoin",
        "/bitcoin-dolar",
        "/bitcoin-euro",
        "/bolivar-venezuelano",
        "/boliviano",
        "/coroa-dinamarquesa",
        "/coroa-norueguesa",
        "/coroa-sueca",
        "/dinar-servio",
        "/dogecoin",
        "/dogecoin-dolar",
        "/dogecoin-euro",
        "/dolar",
        "/dolar-australiano",
        "/dolar-australiano-dolar",
        "/dolar-canadense",
        "/dolar-canadense-dolar",
        "/dolar-euro",
        "/dolar-hong-kong",
        "/dolar-libra",
        "/dolar-neozelandes",
        "/dolar-taiuanes",
        "/dolar-turismo",
        "/ethereum",
        "/ethereum-dolar",
        "/ethereum-euro",
        "/euro",
        "/euro-dolar",
        "/euro-libra",
        "/franco-suico",
        "/franco-suico-dolar",
        "/guarani-paraguaio",
        "/iene",
        "/iene-dolar",
        "/iene-euro",
        "/libra",
        "/libra-dolar",
        "/libra-euro",
        "/litecoin",
        "/litecoin-dolar",
        "/litecoin-euro",
        "/nova-lira-turca",
        "/ouro",
        "/ouro-dolar",
        "/ouro-euro",
        "/peso-argentino",
        "/peso-chileno",
        "/peso-colombiano",
        "/peso-mexicano",
        "/peso-uruguaio",
        "/prata",
        "/prata-dolar",
        "/prata-euro",
        "/rand-sul-africano",
        "/real-dolar",
        "/real-euro",
        "/real-libra",
        "/riyal-saudita",
        "/rublo",
        "/rublo-dolar",
        "/rublo-euro",
        "/rupia-indiana",
        "/sol-do-peru",
        "/solana",
        "/solana-dolar",
        "/solana-euro",
        "/won-sul-coreano",
        "/xrp",
        "/xrp-dolar",
        "/xrp-euro",
        "/yuan",
        "/yuan-dolar",
        "/zloti-polones",
      ],
      disallow: [],
    },
    sitemap: "https://hoooje.com.br/sitemap.xml",
  };
}
