import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://hoooje.com.br",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: "https://hoooje.com.br/baht-tailandes",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.3,
    },
    {
      url: "https://hoooje.com.br/binance-coin",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/binance-coin-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/binance-coin-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/bitcoin",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/bitcoin-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/bitcoin-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/bolivar-venezuelano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/boliviano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/coroa-dinamarquesa",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/coroa-norueguesa",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/coroa-sueca",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dinar-servio",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.4,
    },
    {
      url: "https://hoooje.com.br/dogecoin",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/dogecoin-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/dogecoin-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/dolar-australiano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dolar-australiano-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dolar-canadense",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dolar-canadense-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/dolar-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/dolar-libra",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/dolar-neozelandes",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dolar-taiuanes",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/dolar-turismo",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/ethereum",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/ethereum-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/ethereum-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/euro-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.0,
    },
    {
      url: "https://hoooje.com.br/euro-libra",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/franco-suico",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/franco-suico-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/guarani-paraguaio",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/iene",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/iene-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/iene-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/libra",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/libra-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/libra-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/litecoin",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/litecoin-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/litecoin-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/nova-lira-turca",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/ouro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/ouro-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/ouro-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/peso-argentino",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/peso-chileno",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/peso-mexicano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/peso-uruguaio",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/prata",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.9,
    },
    {
      url: "https://hoooje.com.br/prata-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/prata-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/zand-sul-africano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/real-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/real-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/real-libra",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/riyal-saudita",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/rublo",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.6,
    },
    {
      url: "https://hoooje.com.br/rublo-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.6,
    },
    {
      url: "https://hoooje.com.br/rublo-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.6,
    },
    {
      url: "https://hoooje.com.br/rupia-indiana",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/sol-do-peru",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/solana",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/solana-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/solana-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/won-sul-coreano",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.5,
    },
    {
      url: "https://hoooje.com.br/xrp",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.8,
    },
    {
      url: "https://hoooje.com.br/xrp-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/xrp-euro",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/yuan",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/yuan-dolar",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.7,
    },
    {
      url: "https://hoooje.com.br/zloti-polones",
      lastModified: new Date(),
      changeFrequency: "always",
      priority: 0.4,
    },
  ];
}
